n = input("Enter your name : ")
y = input("Enter your age : ")
c = input("Enter your city : ")
u = input("Enter your university : ")
fc = input("Enter your favorite color : ")
fg = input("Enter your favorite game : ")
ff = input("Enter your favorite food : ")
fm = input("Enter your favorite movie : ")
d = input("Enter your dream job : ")

#This is a simple Mad Libs game where the user inputs various details about themselves.
print (                         )
print (                         )
print("Here is your Mad Libs story:")
print("----------------------------")
print("Your name is " + n + ".")
print("You are " + y + " years old.")
print("You live in " + c + ".")
print("You are a student at " + u + ".")
print("Your favorite color is " + fc + ".")
print("You like to play " + fg + ".")
print("Your favorite food is " + ff + ".")
print("Your favorite movie is " + fm + ".")
print("You want to be a " + d + " when you grow up.")